### ISSUE TITLE
The root directory of homebrew is hard-coded.

### ISSUE THREAD

**Issue by easior** [mrklein/openfoam-os-x#13]
Today, I try to build OpenFOAM 2.3.1 on my MBP. I found your work for it. It's so great! 

However, I also found something defective on your patches because the root directory of homebrew is hard-coded. e.g. there is the following line in OpenFOAM-2.3.1.patch:
``` sh
export BOOST_ARCH_PATH=/usr/local/opt/boost
```
However, my homebrew is installed in to $HOME/Developer. I recommend that all /usr/local in your patches should replaced by \`brew --prefix\`.

E.L.

**Comment by mrklein** [comment]
Here is a citation from Homebrew documentation:

> However do yourself a favor and install to /usr/local. Some things may not build when installed elsewhere. One of the reasons Homebrew just works relative to the competition is because we recommend installing to /usr/local. Pick another prefix at your peril!
