### ISSUE TITLE
SHA256 Mismatch 

### ISSUE THREAD

**Issue by Broekie007** [mrklein/openfoam-os-x#16]
Hi, 

i have the following error during the installation procedure.

~22:36:40$ brew install https://raw.githubusercontent.com/mrklein/openfoam-os-x/master/formulae/parmgridgen.rb
######################################################################## 100.0%
==> Downloading https://github.com/mrklein/ParMGridGen/archive/v0.0.2.tar.gz
==> Downloading from https://codeload.github.com/mrklein/ParMGridGen/tar.gz/v0.0.2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 94fd48e0253c809646b2ce90d9e282dff63393802cdf0d29d21368617599b1c5
Actual: b3875d877def79c5fe37df0c9b1a43a47b3a99e8714f654a44d2010ce338ea93
Archive: /Library/Caches/Homebrew/parmgridgen-0.0.2.tar.gz
To retry an incomplete download, remove the file above.
~22:37:06$ 

Have you any idea how to resolve this?

Tnx in advance!

**Comment by mrklein** [comment]
Hi,

I have updated archive version number but forgotten to update SHA256 sum in formula. I have committed (a6c52a4d421cd470b5d121390710c09e79c1cd5e) new formula file, so the problem should be resolved (in other words try installing formula again).

**Comment by Broekie007** [comment]
Tnx, got it installed and running!
