### ISSUE TITLE
Problem in testing (or installing, I don't know exactly)

### ISSUE THREAD

**Issue by betofc89** [mrklein/openfoam-os-x#20]
Hi,

I'm trying to install OpenFOAM 3.0.x in my Mac OS X El Captain, but I'm struggling to get it right. In the "Testing installation" manual (https://github.com/mrklein/openfoam-os-x/wiki/Testing-installation), when it asks me to use the "run" command, the terminal sends me back the following:

`-bash: cd: /Users/roberto/OpenFOAM/roberto-3.0.x/run: No such file or directory`

I followed all the steps contained in https://github.com/mrklein/openfoam-os-x/wiki/OpenFOAM-release-&-Homebrew , and I'm suspecting that the error above has something to do with the "Build OpenFOAM" section. In this section, the tutorial asks me to run the command:

`$ mkdir -p $HOME/.OpenFOAM`

but when I run the abover line in the terminal, nothing happens, in other words, no directory is created in the $HOME location. I can't figure what I'm doing wrong.

Thanks in advance,

Roberto

**Comment by mrklein** [comment]
Hi,

Sorry I forgot `mkdir -p "$FOAM_RUN"` before `run` command in [Testing installation](https://github.com/mrklein/openfoam-os-x/wiki/Testing-installation) guide. I have added it to the list of commands.

Concerning `$ mkdir -p $HOME/.OpenFOAM`, I do not know how you check if directory is created. `.OpenFOAM` is hidden folder, so usually you do not see it in Finder (unless you have `com.apple.finder AppleShowAllFiles` set to `TRUE`), I you use `ls`, then you need to use `-a` flag to see this folder in listing.

**Comment by mrklein** [comment]
Guess, "thumbs up" means "issue can be closed.
