### ISSUE TITLE
Unable to install v4.0 on Sierra

### ISSUE THREAD

**Issue by Simsey** [mrklein/openfoam-os-x#22]
Hey, first of all thank you for your effort to support the community!

I tried to install OpenFOAM 4.x on a freshly installed system. Maybe my problem is quite simple, as the files I use differ from the link you provided in the wiki (OpenFOAM release & Homebrew). I followed your guide and replaced 

`curl -L http://downloads.sourceforge.net/foam/OpenFOAM-<VER>.tgz > OpenFOAM-<VER>.tgz
`

with

`wget -O - http://download.openfoam.org/source/4-0 | tar xvz
`
as there is no http://downloads.sourceforge.net/foam/OpenFOAM-4.0.tgz available.

I thought I have to use the 4.x patch but it's not possible to apply it.
```
curl -L https://raw.githubusercontent.com/mrklein/openfoam-os-x/master/OpenFOAM-4.x-7dce081.patch > OpenFOAM-4.x.patch
git apply OpenFOAM-4.x.patch 
error: patch failed: etc/bashrc:42
error: etc/bashrc: patch does not apply
error: patch failed: src/renumber/SloanRenumber/Make/options:1
error: src/renumber/SloanRenumber/Make/options: patch does not apply
```

 OpenFOAM-4.0.patch applies without errors.

./Allwmake returns:
```
xcrun cc -arch x86_64 -Ddarwin64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -O3   -fPIC -isysroot  -Wno-unused-function dirToString.c -o /Users/xyz/OpenFOAM/OpenFOAM-4.0/wmake/platforms/darwin64Clang/dirToString
clang: warning: no such sysroot directory: '-Wno-unused-function'
dirToString.c:43:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [/Users/xyz/OpenFOAM/OpenFOAM-4.0/wmake/platforms/darwin64Clang/dirToString] Error 1
```

Additional information:
```
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323
```

clang++ --version
```
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

brew -v
```
Homebrew 1.0.6
Homebrew/homebrew-core (git revision 8cff; last commit 2016-10-06)
```

Thanks in advance!

**Comment by mrklein** [comment]
Hi,

It is normal that patch for 4.x can not be applied on 4.0 sources (since 4.x source tree state differs from 4.0).

I see the error (it is caused by empty output of `xcrun --show-sdk-path`), so you have choice:
- Install OpenFOAM 4.x, where the error is fixed.
- Wait till 4.0 patch is fixed (couple of days, I think).

Thanks for the installation guide corrections, will try to add them (or create separate guide for 4.x branch).

**Comment by Simsey** [comment]
Thanks for your fast response! I'll wait and try it again. (;

**Comment by mrklein** [comment]
I have pushed update for 4.0 patch, could you test it (unfortunately I do not have access to Mac without Xcode)?

**Comment by Simsey** [comment]
Thank you very much! That solved the problem!
