### ISSUE TITLE
Can't run icoFoam or blockMesh?

### ISSUE THREAD

**Issue by APCoding** [mrklein/openfoam-os-x#23]
Hi!

I love your recipe. Thank you! The installation seemed to be fine, but apparently running icoFoam or blockMesh throws a big scary command not found error. FoamRunTutorials works fine, which shows at least the installation is working. Had this problem before? How'd you fix it? Thanks for your help! I attached the output of ./Allmwake.
[log.txt](https://github.com/mrklein/openfoam-os-x/files/537748/log.txt)
I'm using macOS Sierra, and I'm installing OpenFOAM 4.0.

**Comment by mrklein** [comment]
Hi,

Command not found error is a result of failed build (well, part of OpenFOAM was built but due to error in surfMesh everything depending on the library is missing). `foamRunTutorials` seems to be running but in fact it just redirects error messages to corresponding log files.

There is something wrong with flex, so could you post:

1. Output of `xcrun c++ --version` command.
2. Output of `xcrun flex --version` command.
3. Output of `flex --version` command.

**Comment by APCoding** [comment]
Thanks for the fast response! Here are the outputs:

1. `Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`
2. `flex 2.5.35 Apple(flex-31)`
3. `flex 2.6.0`

**Comment by mrklein** [comment]
As I suspected: you have third party flex in your path, it is not compatible with headers, which come with Apple's flex.

There are several solutions for the problem:

1. Uninstall third party flex.
2. Remove third party flex from PATH for the time of compilation.
3. Open `wmake/rules/General/flex++` file, change `flex` to `xcrun flex` there.

After resolution of `flex` problem, you can run `Allwmake` script again, this time all solvers and utilities should be compiled, so you can use `blockMesh` and `icoFoam`.

**Comment by APCoding** [comment]
Thanks! It worked!

**Comment by jnesemu** [comment]
Hi!
hi friends,
i installed OpenFOAM-4.0 in ubuntu 16.04 in linux but when i try to run blockmesh command get blockMesh "command not found problem". The installation seemed to be fine, but apparently running icoFoam or blockMesh throws a big scary command not found error. when run raraview command runs which shows at least the installation is working. Had this problem before? How'd you fix it? Thanks for your help!

**Comment by jnesemu** [comment]
Hi friends,
when run the;
    1. Output of xcrun c++ --version command.
    2. Output of xcrun flex --version command.
    3. Output of flex --version command.
Here are the outputs:
1. not found
2. not found
3. flex 2.6.0
thanks in advance.

**Comment by mrklein** [comment]
@jnesemu 

1. Ubuntu and macOS are completely different operating systems.
2. The repository is an effort to allow compilation of OpenFOAM(R) on macOS.
3. Ubuntu is officially supported by Foundation (so, you can post issues in their bug tracker).
4. Finally, `"command not found problem"` is in general "environment is not set up" problem.
