### ISSUE TITLE
question on commits

### ISSUE THREAD

**Issue by JennaVergeynst** [mrklein/openfoam-os-x#26]
Hi,

I'm following the OpenFOAM dev & Homebrew instructions to install OpenFOAM on my mac.

Now, I'm stuck with the part 'Check out sources':
   $ git checkout -b local-install <commit>
I suppose that I have to replace <commit> by the correct commit number? But how do I know what to fill in here, can anyone explain me?

Thanks!
Jenna

**Comment by mrklein** [comment]
Hi,

See Note 2 (https://github.com/mrklein/openfoam-os-x/wiki/OpenFOAM-dev%20&%20Homebrew#note-2). Latest patch is for commit b45452d (https://raw.githubusercontent.com/mrklein/openfoam-os-x/master/OpenFOAM-dev-b45452d.patch).

**Comment by JennaVergeynst** [comment]
Hmm... when I do:
`git checkout -b local-install b45452d`

I get the following error:
`fatal: Not a git repository (or any parent up to mount point /Users/jennavergeynst/OpenFOAM)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`

Any idea...?

**Comment by mrklein** [comment]
Oh. One step is missing: you need `cd OpenFOAM-dev` after `git clone git@github.com:OpenFOAM/OpenFOAM-dev.git`. Thanks for reporting, I have added it to the guide.

**Comment by JennaVergeynst** [comment]
This works, thanks!

But I have still a problem. When testing the installation with the parallel case, it says:
`decomposePar: command not found `

**Comment by JennaVergeynst** [comment]
And also, I installed the binary Paraview release in /Applications folder, but when typing paraview it says: command not found...

**Comment by mrklein** [comment]
Unfortunately I do not deduce where the problem is from the information you have posted. Could you add...

1. `log.Allwmake` file, which was created during compilation.
2. Output of `export | grep -E '(FOAM_|WM_)' | sed -e s#$HOME#\$HOME# -e s#$USER#\$USER#` in the terminal, where you are trying to run `decomposePar`.
3. Output of `export -f | grep paraview` in the terminal, where you are trying to start paraview.

**Comment by JennaVergeynst** [comment]
Ah, there is already an error in log.Allwmake:
`xcrun cc -arch x86_64 -Ddarwin64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -O3   -fPIC -isysroot  -Wno-unused-function dirToString.c -o /Users/jennavergeynst/OpenFOAM/OpenFOAM-dev/wmake/platforms/darwin64Clang/dirToString
clang: warning: no such sysroot directory: '-Wno-unused-function'
dirToString.c:43:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [/Users/jennavergeynst/OpenFOAM/OpenFOAM-dev/wmake/platforms/darwin64Clang/dirToString] Error 1
`
And also, when opening the terminal (and running .bash_profile), it says: 
`-bash: /Users/jennavergeynst/OpenFOAM/OpenFOAM-2.B.C/etc/bashrc: No such file or directory`
So probably something went wrong in post-configuration as well...

**Comment by mrklein** [comment]
Concerning compilation error, you have several choices:

1. Wait a little bit till I update patch and restart whole installation process, i.e. delete OpenFOAM-dev folder and start from checking out sources (https://github.com/mrklein/openfoam-os-x/wiki/OpenFOAM-dev-&-Homebrew#check-out-sources).
2. Open `wmake/rules/darwin64Clang/c`, locate `cFLAGS      = $(GFLAGS) $(cWARN) $(cOPT) $(cDBUG) $(LIB_HEADER_DIRS) -fPIC -isysroot $(OSX_SDK_PATH)` line, remove `-isysroot $(OSX_SDK_PATH)` part. Repeat the same thing for `wmake/rules/darwin64Clang/c++`: locate line `c++FLAGS    = $(GFLAGS) $(c++WARN) $(c++OPT) $(c++DBUG) $(ptFLAGS) $(LIB_HEADER_DIRS) -fPIC -isysroot $(OSX_SDK_PATH)`, remove `-isysroot $(OSX_SDK_PATH)` part. Recompile OpenFOAM.

Concerning error message in terminal, you have to substitute `2.B.C` in `/Users/jennavergeynst/OpenFOAM/OpenFOAM-2.B.C/etc/bashrc` with `dev`, since you are using dev-branch.

**Comment by JennaVergeynst** [comment]
I tried option 2 and recompiled, but decomposePar still not working. So maybe I should restart the installation? However, the output from `export | grep -E '(FOAM_|WM_)' | sed -e s#$HOME#\$HOME# -e s#$USER#\$USER#` is:

`declare -x FOAM_APP="$HOME/OpenFOAM/OpenFOAM-dev/applications"
declare -x FOAM_APPBIN="$HOME/OpenFOAM/OpenFOAM-dev/platforms/darwin64ClangDPInt32Opt/bin"
declare -x FOAM_ETC="$HOME/OpenFOAM/OpenFOAM-dev/etc"
declare -x FOAM_EXT_LIBBIN="/platforms/darwin64ClangDPInt32/lib"
declare -x FOAM_INST_DIR="$HOME/OpenFOAM"
declare -x FOAM_JOB_DIR="$HOME/OpenFOAM/jobControl"
declare -x FOAM_LIBBIN="$HOME/OpenFOAM/OpenFOAM-dev/platforms/darwin64ClangDPInt32Opt/lib"
declare -x FOAM_MPI="openmpi-system"
declare -x FOAM_RUN="$HOME/OpenFOAM/$USER-dev/run"
declare -x FOAM_SETTINGS="WM_NCOMPPROCS=4"
declare -x FOAM_SIGFPE=""
declare -x FOAM_SITE_APPBIN="$HOME/OpenFOAM/site/dev/platforms/darwin64ClangDPInt32Opt/bin"
declare -x FOAM_SITE_LIBBIN="$HOME/OpenFOAM/site/dev/platforms/darwin64ClangDPInt32Opt/lib"
declare -x FOAM_SOLVERS="$HOME/OpenFOAM/OpenFOAM-dev/applications/solvers"
declare -x FOAM_SRC="$HOME/OpenFOAM/OpenFOAM-dev/src"
declare -x FOAM_TUTORIALS="$HOME/OpenFOAM/OpenFOAM-dev/tutorials"
declare -x FOAM_USER_APPBIN="$HOME/OpenFOAM/$USER-dev/platforms/darwin64ClangDPInt32Opt/bin"
declare -x FOAM_USER_LIBBIN="$HOME/OpenFOAM/$USER-dev/platforms/darwin64ClangDPInt32Opt/lib"
declare -x FOAM_UTILITIES="$HOME/OpenFOAM/OpenFOAM-dev/applications/utilities"
declare -x WM_ARCH="darwin64"
declare -x WM_ARCH_OPTION="64"
declare -x WM_CC="clang"
declare -x WM_COMPILER="Clang"
declare -x WM_COMPILER_LIB_ARCH="64"
declare -x WM_COMPILER_TYPE="system"
declare -x WM_COMPILE_OPTION="Opt"
declare -x WM_CXX="clang++"
declare -x WM_DIR="$HOME/OpenFOAM/OpenFOAM-dev/wmake"
declare -x WM_LABEL_OPTION="Int32"
declare -x WM_LABEL_SIZE="32"
declare -x WM_LINK_LANGUAGE="c++"
declare -x WM_MPLIB="SYSTEMOPENMPI"
declare -x WM_NCOMPPROCS="4"
declare -x WM_OPTIONS="darwin64ClangDPInt32Opt"
declare -x WM_OSTYPE="POSIX"
declare -x WM_PRECISION_OPTION="DP"
declare -x WM_PROJECT="OpenFOAM"
declare -x WM_PROJECT_DIR="$HOME/OpenFOAM/OpenFOAM-dev"
declare -x WM_PROJECT_INST_DIR="$HOME/OpenFOAM"
declare -x WM_PROJECT_USER_DIR="$HOME/OpenFOAM/$USER-dev"
declare -x WM_PROJECT_VERSION="dev"`

As for paraview, no output when I do `export -f | grep paraview `. But here I think I just miss the link between openfoam and paraview... it is installed in the /Application folder, but I think I have to add a path to it somewhere... But where?

**Comment by mrklein** [comment]
1. Can you again post your `log.Allwmake`? Your environment is set up, yet there is no decomposePar, so it seems, there is another error during compilation.

2. What is the name of paraview application? During environment setup (`source etc/bashrc`) I check for /Applications/paraview.app, and export function paraview like this:

```sh
if [ -d "/Applications/paraview.app" ];
then
    [ "$FOAM_VERBOSE" -a "$PS1" ] && echo "Using /Applications/paraview.app"

    paraview () {
        "/Applications/paraview.app/Contents/MacOS/paraview" "$@"
    }

    export -f paraview
else
...
```

**Comment by JennaVergeynst** [comment]
Here you have the log file… too long to copy it.It is ParaView-5.2.0-RC2.Is the code you’ve written here to be copied in my .bash_profile file?Thanks a lot...On 27 Oct 2016, at 14:49, Alexey Matveichev <notifications@github.com> wrote:
Can you again post your log.Allwmake? Your environment is set up, yet there is no decomposePar, so it seems, there is another error during compilation.
What is the name of paraview application? During environment setup (source etc/bashrc) I check for /Applications/paraview.app, and export function paraview like this:


if [ -d "/Applications/paraview.app" ];
then
    [ "$FOAM_VERBOSE" -a "$PS1" ] && echo "Using /Applications/paraview.app"

    paraview () {
        "/Applications/paraview.app/Contents/MacOS/paraview" "$@"
    }

    export -f paraview
else
...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrklein/openfoam-os-x","title":"mrklein/openfoam-os-x","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/mrklein/openfoam-os-x" class="">https://github.com/mrklein/openfoam-os-x</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mrklein in #26: 1. Can you again post your `log.Allwmake`? Your environment is set up, yet there is no decomposePar, so it seems, there is another error during compilation.\r\n\r\n2. What is the name of paraview application? During environment setup (`source etc/bashrc`) I check for /Applications/paraview.app, and export function paraview like this:\r\n\r\n```sh\r\nif [ -d \"/Applications/paraview.app\" ];\r\nthen\r\n    [ \"$FOAM_VERBOSE\" -a \"$PS1\" ] \u0026\u0026 echo \"Using /Applications/paraview.app\"\r\n\r\n    paraview () {\r\n        \"/Applications/paraview.app/Contents/MacOS/paraview\" \"$@\"\r\n    }\r\n\r\n    export -f paraview\r\nelse\r\n...\r\n```"}],"action":{"name":"View Issue","url":"<a href="https://github.com/mrklein/openfoam-os-x/issues/26#issuecomment-256631538" class="">https://github.com/mrklein/openfoam-os-x/issues/26#issuecomment-256631538</a>"}}}

**Comment by mrklein** [comment]
Where is the log-file? You can attach files to comments, there is no need to copy-pasted log-file to message.

No, code I have posted is a part of patch, it is executed during `source etc/bashrc` stage.

**Comment by JennaVergeynst** [comment]
[log.Allwmake.TXT](https://github.com/mrklein/openfoam-os-x/files/556494/log.Allwmake.TXT)
Here it should be.

**Comment by mrklein** [comment]
Since errors are during `flex` run, could you post output of

1. `flex --version`
2. `xcrun flex --version`

(it seems, you have third party `flex` in your path and it conflicts with Apple's headers, see #23 )

**Comment by JennaVergeynst** [comment]
Here you go:

1. `flex 2.6.0`

2. `flex 2.5.35 Apple(flex-31)`

**Comment by mrklein** [comment]
As I expected. You can find solution to this problem here - https://github.com/mrklein/openfoam-os-x/issues/23#issuecomment-255097899.

Maybe in the nearest future solution 3 will find its way to the patch to avoid problems with third party flex.

**Comment by JennaVergeynst** [comment]
Hi again,

I'm trying to solve it this way, Allwmake is running. Thanks for the good advice.

There is one thing I still don't get: how do I get the paraview working in OpenFOAM? In which script do I have to put the code you've written there?

**Comment by JennaVergeynst** [comment]
Also, after recompiling openFoam now, I test decomposePar again and now it runs, but there is still a FOAM FATAL ERROR:

`Cannot find file "points" in directory "polyMesh" in times 0.5 down to constant

    From function Foam::word Foam::Time::findInstance(const Foam::fileName &, const Foam::word &, const IOobject::readOption, const Foam::word &) const
    in file db/Time/findInstance.C at line 182.

FOAM exiting
`
Is this still a compiling problem?

**Comment by mrklein** [comment]
Guess, paraview problem is related to the version (it is not release yet, just release candidate, so application is called ParaView-5.2.0-RC2 and now paraview as usual. So, you have several possibilities:

1. Rename `ParaView-5.2.0-RC2` to `paraview`.
2. Open `etc/config.sh/mac/paraview` file, change every `paraview.app` to `ParaView-5.2.0-RC2.app`.

**Comment by mrklein** [comment]
`decomposePar` (or what ever you are trying to run) for some reason can not find your mesh. I do not have the error. Can you describe steps to reproduce it?

**Comment by JennaVergeynst** [comment]
So in the cavity tutorial, I do the test case:

`$foamRunTutorials 
$cat > system/decomposeParDict
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      decomposeParDict;
}

numberOfSubdomains 4;

method          scotch;
^D
$ decomposePar`

**Comment by mrklein** [comment]
`foamRunTutorials` command created `log.blockMesh` and `log.icoFoam` files, could you post them?

**Comment by JennaVergeynst** [comment]
[log.blockMesh.TXT](https://github.com/mrklein/openfoam-os-x/files/558465/log.blockMesh.TXT)
[log.icoFoam.TXT](https://github.com/mrklein/openfoam-os-x/files/558464/log.icoFoam.TXT)
Aha... both say 'command not found'... However, if I do blockMesh or icoFoam, both run...

**Comment by mrklein** [comment]
So let's try to summarise the problem. Here are my questions:

1. Do I get it right that you can run blockMesh and icoFoam by hand?
2. Do you get the error when run decomposePar after running blockMesh by hand?
3. If you execute `foamRunTutorials` in case folder, you always get `Command not found` error in created log-files?
4. What is the output of `sw_vers` command?
5. What is the output of `csrutil status` command?

**Comment by JennaVergeynst** [comment]
Hey,

I found the error: had written method 'sotch' instead of 'scotch', which caused the command not found errors. So everything should work now (I hope) :-)

Thanks a lot for the great help!
Jenna
