### ISSUE TITLE
extend disk space

### ISSUE THREAD

**Issue by JennaVergeynst** [mrklein/openfoam-os-x#28]
Hi,

I have the openfoam dev version installed. Is it possible to extend disk space after installation?
I get the error:
`the user's disk quota is exhausted`

Thanks,
Jenna

**Comment by mrklein** [comment]
Did you try `hdiutil resize`? Something like:

1. Umount disk image (`hdiutil detach $HOME/OpenFOAM`)
2. Issue command (`hdiutil resize 64G $HOME/OpenFOAM.sparsebundle`)

Then as usual mount disk image, issue `source $HOME/OpenFOAM/OpenFOAM-dev/etc/bashrc`, etc.

**Comment by mrklein** [comment]
Though it is rather strange, that OpenFOAM-dev exhausted your 8.3G of disk image. Could you post output of `df -h | grep OpenFOAM`?

**Comment by JennaVergeynst** [comment]
`/dev/disk2s2                       8.0Gi  8.0Gi  1.1Mi   100%  2091542      274  100%   /Users/jennavergeynst/OpenFOAM
`

**Comment by mrklein** [comment]
It is really occupied ;) Maybe you have Opt, Prof, and Debug versions compiled (or you store simulation results on the disk image). So, you can try `hdiutil resize` command I have posted above (hope 64 G will be enough).

**Comment by JennaVergeynst** [comment]
resize command gives:
`hdiutil: resize: only a single file can be specified
Usage:	hdiutil resize <sizespec> [options] <image>
	hdiutil resize -help`

**Comment by mrklein** [comment]
Could you post whole output? I.e. with the command you are entering. Right now all I can see that either you made mistake specifying new size, or made a mistake specifying image name.

**Comment by JennaVergeynst** [comment]
`(work)bw10pc55:~ jennavergeynst$ hdiutil resize 64G $HOME/OpenFOAM.sparsebundle
hdiutil: resize: only a single file can be specified
Usage:	hdiutil resize <sizespec> [options] <image>
	hdiutil resize -help`

**Comment by JennaVergeynst** [comment]
Ah, excuse me, I forgot -size!

**Comment by JennaVergeynst** [comment]
But then still:
`(work)bw10pc55:~ jennavergeynst$ hdiutil resize -size 64g $HOME/OpenFOAM.sparsebundle
hdiutil: resize: failed. Resource temporarily unavailable (35)`

**Comment by mrklein** [comment]
So this time size specification is OK.

This is quote from `hdiutil` man page:

```
     [EAGAIN]           Resource temporarily unavailable.  As of Mac OS X 10.5,
                        DiskImages uses read/write locks on its image files to
                        prevent images from being attached on more than one
                        machine at a time (e.g. over the network).  EAGAIN is
                        returned if the appropriate read or write lock can't be
                        obtained.
```

My guess: your image is still mounted. So detach it with `hdiutil detach` command or using Finder.

**Comment by JennaVergeynst** [comment]
Ah, I see, I detached, but then in the meantime opened it again in another screen. 
Now it seems everything's fine!

Another question (or should I open a new issue?): can I change the openfoam version, without reinstalling everything? It's now the development version, maybe I would need an older verion to correspond with our cluster version here....

**Comment by JennaVergeynst** [comment]
O and yes, I'm storing results on the disk image... How can I change this, to avoid overloading?

**Comment by mrklein** [comment]
You can compile another OpenFOAM version on the same disk image, concerning installation guide skip all steps till "Extract sources".

Guess, you run your cases in `$FOAM_RUN` folder, so you can do something like: https://github.com/mrklein/openfoam-os-x/wiki/Post-configuration#foam_run-folder. `2.B.C` in your case is `dev`. Usually, cases do not need case-sensitive file system, so you can run them outside of disk image.

**Comment by JennaVergeynst** [comment]
So if I want version 3.0.x, it would be:
`git clone git@github.com:OpenFOAM/OpenFOAM-3.0.x.git`?
Gives following error for me:

`Cloning into 'OpenFOAM-3.0.x'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by mrklein** [comment]
If you can not clone repo using ssh protocol, use https.

**Comment by JennaVergeynst** [comment]
Great, thanks for the good help!
