### ISSUE TITLE
Typo in openfoam-env-setup.sh

### ISSUE THREAD

**Issue by ninjascientist** [mrklein/openfoam-os-x#30]
I just noticed that on the 13th line of the script there is a typo (apparently).

It is written as:
readonly FOAM_RELEASE_FILE="${FOAM_RELESE_FILE:-"$HOME/.OpenFOAM/OpenFOAM-release"}"

I believe the intention was for it to be written as:
readonly FOAM_RELEASE_FILE="${FOAM_RELE**A**SE_FILE:-"$HOME/.OpenFOAM/OpenFOAM-release"}"

**Comment by mrklein** [comment]
You are right. Thank you for reporting.
