### ISSUE TITLE
foamMonitor: Gnuplot terminal not set correctly

### ISSUE THREAD

**Issue by cgramesp** [mrklein/openfoam-os-x#37]
Gnuplot Terminal is not set correctly in `$WM_PROJECT_DIR/bin/foamMonitor`.

line 69 should be set to:
    `set term selected_terminal 1 font "helvetica,17" linewidth 1.5 persist noraise`

**Comment by mrklein** [comment]
Thanks for reporting. Will fix as soon as possible.

**Comment by mrklein** [comment]
Fixed in d6b822f
