### ISSUE TITLE
Mac OS High Sierra Xcode Beta 9 - tutorial test fails `_rm~all_': not a valid identifier

### ISSUE THREAD

**Issue by ajl42** [mrklein/openfoam-os-x#39]
Hi,
         I've been beta testing Mac OS high sierra with Xcode.  Openfoam compiled fine, only one small glitch running the cavity tutorial test.  I obtain the following error:

~/OpenFOAM/OpenFOAM-5.x/etc/config.sh/bash_completion: line 6658: `_rm~all_': not a valid identifier

To get the tutorials running I edited the bash_completion file and removed the ~.  I'm not sure if this is the correct fix.

Many thanks for your wiki and compilation patches.  

Best wishes,

Andy.

**Comment by mrklein** [comment]
Hi,

Thanks for reporting.

In fact, I have already mentioned this problem in issue #35. Your proposed fix is fine, in mine, I renamed _rm~all_ into _rm_all_.

Regards

**Comment by ajl42** [comment]
Hi Alexey, thanks.  

Andy.

**Comment by mrklein** [comment]
Fixed in d6b822f
