### ISSUE TITLE
OF 5.0 git version running parallel gives dyld: Symbol not found: ___intel_sse2_strdup error?

### ISSUE THREAD

**Issue by ajl42** [mrklein/openfoam-os-x#42]
Hi, 
        thanks for all your great work!  OF 5 compiles well and runs well on a single node.   When I try to run parallel using the latest mpirun (Open MPI) 2.1.1 and OF 5 it throws the following error:

dyld: lazy symbol binding failed: Symbol not found: ___intel_sse2_strdup
  Referenced from: /Users/openmpi/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt64Opt/lib/openmpi-system/libPstream.dylib
  Expected in: flat namespace

dyld: Symbol not found: ___intel_sse2_strdup
  Referenced from: /Users/openmpi/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt64Opt/lib/openmpi-system/libPstream.dylib
  Expected in: flat namespace

Any ideas?

Best wishes,

Andy.

**Comment by mrklein** [comment]
Hi,

Thank you for the report. Unfortunately, I can not reproduce the error (I even compiled 64-bit label version). Could you provide more details on the error?

**Comment by ajl42** [comment]
Hi Alexey, 

                    thanks for the quick reply.  Here’s my log file, there’s one warning that may 
be the cause, line 43.  

Thanks,

Andy.

**Comment by ajl42** [comment]
Hi Alexey, yes, sorry, should have mentioned it’s zipped down:



Best wishes,

Andy.

**Comment by mrklein** [comment]
Hi,

OK, still no log-file, but let's start with simpler questions:
1. Do you have Intel compilers installed?
2. Could you post output of `mpicc --showme`?

Cause, in fact, latest OpenMPI is 3.1.0 and Google search on the symbol errors you have posted leads to threads, where people had problems with Intel compilers.

**Comment by ajl42** [comment]
Hi,

        answers to questions at the bottom of this email; here are the warning lines from my log file:

Lines 33 - 40

Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32OptSYSTEMOPENMPI/lib \
	    -L/Users/andrewlowe/FDS6_6/FDS6_6/bin/openmpi_64/lib -lmpi -lopen-rte -lopen-pal -lm -lz  -o /Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32Opt/lib/openmpi-system/libPstream.dylib

ld: warning: directory not found for option '-L/Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32OptSYSTEMOPENMPI/lib'

Allwmake libo src/OSspecific/POSIX
wmake libo .
Making dependency list for source file printStack.C
Making dependency list for source file fileMonitor.C
Making dependency list for source file memInfo.C


Lines 2828 - 2835

xcrun c++ -arch x86_64 -std=c++11 -Ddarwin64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wno-unused-parameter -Wno-overloaded-virtual -Wno-unused-variable -Wno-unused-local-typedef -Wno-invalid-offsetof -Wno-deprecated-register -Wno-undefined-var-template -O3  -DNoRepository -ftemplate-depth-100 -DOMPI_SKIP_MPICXX -I/Users/andrewlowe/FDS6_6/FDS6_6/bin/openmpi_64/include -I/usr/local/opt/scotch/include -I../decompositionMethods/lnInclude -IlnInclude -I. -I/Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/src/OpenFOAM/lnInclude -I/Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/src/OSspecific/POSIX/lnInclude   -fPIC -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -Wl,-dylib,-undefined,dynamic_lookup /Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32OptSYSTEMOPENMPI/src/parallel/decompose/ptscotchDecomp/ptscotchDecomp.o -L/Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32OptSYSTEMOPENMPI/lib \
	    -L/usr/local/opt/scotch/lib -lptscotch -lptscotcherrexit -lscotch  -o /Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32Opt/lib/openmpi-system/libptscotchDecomp.dylib

ld: warning: directory not found for option '-L/Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32OptSYSTEMOPENMPI/lib'

Allwmake src/parallel/decompose/metisDecomp
    using METIS_ARCH_PATH=/usr/local/opt/metis
Making dependency list for source file metisDecomp.C
xcrun c++ -arch x86_64 -std=c++11 -Ddarwin64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wno-unused-parameter -Wno-overloaded-virtual -Wno-unused-variable -Wno-unused-local-typedef -Wno-invalid-offsetof -Wno-deprecated-register -Wno-undefined-var-template -O3  -DNoRepository -ftemplate-depth-100 -I/usr/local/opt/metis/include -I../decompositionMethods/lnInclude -IlnInclude -I. -I/Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/src/OpenFOAM/lnInclude -I/Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/src/OSspecific/POSIX/lnInclude   -fPIC -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -c metisDecomp.C -o /Users/andrewlowe/OpenFOAM/OpenFOAM-5.x/platforms/darwin64ClangDPInt32Opt/src/parallel/decompose/metisDecomp/metisDecomp.o


The log file is 4Mb, I can send this if the above isn’t helpful.

Many thanks,

Andy.



> On 7 Jun 2018, at 11:45, Alexey Matveichev <notifications@github.com> wrote:
> 
> Hi,
> 
> OK, still no log-file, but let's start with simpler questions:
> 
> Do you have Intel compilers installed?

No, using gcc from homebrew.

> Could you post output of mpicc --showme?
> Cause, in fact, latest OpenMPI is 3.1.0 and Google search on the symbol errors you have posted leads to threads, where people had problems with Intel compilers.
> 
> —
> 

$ mpicc --showme?
clang -I/usr/local/Cellar/open-mpi/3.1.0/include -L/usr/local/opt/libevent/lib -L/usr/local/Cellar/open-mpi/3.1.0/lib -lmpi

**Comment by mrklein** [comment]
If there is no more warnings in log-file, no need to attach it. Warnings you have posted can be safely ignored (there could be also warning about CGAL, they also can be ignored).

Though, it seems there is a conflict between libraries. During OpenFOAM compilation OpenMPI from FDS distributive was used:

```
...
-L.../FDS6_6/FDS6_6/bin/openmpi_64/lib -lmpi -lopen-rte -lopen-pal
...
```

This OpenMPI distribution provides libraries with `__intel_sse2_strdup` (and other `__intel_*` symbols). Yet output from mpicc shows, that now you utilise OpenMPI installed with Homebrew.

Do you still have FDS installed? Could you use mpirun from that distribution?

**Comment by ajl42** [comment]
Yes I do; I’ll try that mpirun.

Andy

**Comment by ajl42** [comment]
Hi Alexey, 

                 it didn’t work with the FDS6_6 mpirun.   NIST ( FDS6 developers ) pre-compile mpirun for users of FDS6 so general users of the open source code don’t need to compile it.  This is the problem, I’ll compile again from a clean fresh start.   Thanks for your help.

Best wishes,

Andy.
