### ISSUE TITLE
OF7 compilation: in UPstream.H:42:10: fatal error: 'labelList.H' file not found

### ISSUE THREAD

**Issue by saneku** [mrklein/openfoam-os-x#49]
Hello!
I was trying to compile OFv7 (OpenFOAM(R) git version & Homebrew) using the provided instructions and I stuck on Allwmake command with the following error:
_OpenFOAM/OpenFOAM-7/src/OpenFOAM/lnInclude/UPstream.H:42:10: fatal error: 'labelList.H' file not found_
I understand that the link on labelList.H does not exist in the _lnInclude_ directory.
What is the right way to add it?
Could you please advise?
Thanks!

**Comment by mrklein** [comment]
Hi!

I have tried to reproduce the error and, unfortunately, did not succeed.

The error looks like an attempt to build OpenFOAM on case-insensitive file system. Or maybe sources were first cloned to case-insensitive filesystem and then moved to disk image.

Could you list the steps you have performed to get the error?

**Comment by saneku** [comment]
Hello!
I repeated the procedure again and it worked.
Probably, the error was in "./Allwmake > log.Allwmake 2>&1" which I canceled after a few seconds.
And it caused not all header files to be linked in lnInclude directory.
Thanks very much!
