### ISSUE TITLE
v1912 patch doesn't look for paraview.app

### ISSUE THREAD

**Issue by BrushXue** [mrklein/openfoam-os-x#51]
First I would like to appreciate your great work. v1912 can compile with 64 bit labels without extra patches. OpenFOAM itself looks good.
However the paraview-plugin wasn't compiled.(I looked into the patch, this is not 64-bit label related. It just doesn't link paraview.app)
```
==> skip paraview-plugin (could not determine target or major.minor version)
    PV_PLUGIN_PATH=???

WARNING: skip ParaView Catalyst (missing or incorrrect ParaView)
======================================================================
```
I saw that you have config.sh/mac/paraview in version 7 patch which is different. Is there any difference between .org and .com version? Thanks.

**Comment by mrklein** [comment]
Hi,

You are right, while dealing with `DYLD_LIBRARY_PATH` I have forgotten about ParaView.

You can use attached patch [1] to fix the problem, if you do not want to redo build procedure. Later I will update the whole patch for v1912.

1. [lost-paraview.patch.gz](https://github.com/mrklein/openfoam-os-x/files/4493170/lost-paraview.patch.gz)

**Comment by mrklein** [comment]
It was a little bit too fast for the previous message. 

[This patch](https://github.com/mrklein/openfoam-os-x/files/4501855/lost-paraview.patch.gz) contains files with function/alias setup for ParaView.

**Comment by BrushXue** [comment]
I applied the patch but still got the same error
```
==> skip paraview-plugin (could not determine target or major.minor version)
WARNING: skip ParaView Catalyst (missing or incorrrect ParaView)
```
The paraview app was found
```
echo $_paraviews
/Applications/ParaView-5.8.0.app
```

**Comment by mrklein** [comment]
If you need `paraview-plugin` and `ParaView Catalyst`, you should try building ParaView from sources (this way you have development headers). Since I use built-in ParaView plug-in for visualisation, and do not use Catalyst, it would be difficult for me to test these parts.

**Comment by BrushXue** [comment]
Yeah you are right. I just need paraFoam command and that's enough. Thanks.

**Comment by mrklein** [comment]
`paraFoam` is usable (it falls-back to build-in plug-in automatically). Unfortunately, I do not use `paraFoam` directly neither on Linux, nor on OS X, I have `alias pf='paraFoam -builtin'`, as, usually, I am quite lazy to build OpenFOAM's plug-in.

**Comment by BrushXue** [comment]
> I am quite lazy to build OpenFOAM's plug-in.

I agree, especially for the OpenCFD version. They are adding so many useless third party libraries to build useless plug-ins and I always disable them on Linux. Anyway, thanks for your great work!
