### ISSUE TITLE
OpenFOAM-v2006

### ISSUE THREAD

**Issue by matteoicardi** [mrklein/openfoam-os-x#53]
Thanks for the great work of this repo, any chance of having the patch for v2006 anytime soon? I tried to adapt the v1912 but I didn't manage to

**Comment by mrklein** [comment]
Hi,

In fact, for basic functionality you do not need patches. Previous patch was to fix minor issues with C++14, CGAL, PavaView, and SIP. Guess, it could be adapted for the new version in a week.

**Comment by mrklein** [comment]
@matteoicardi did you have time to test the patch for v2006?

**Comment by matteoicardi** [comment]
it works a treat! thanks! just had to do some minor changes because I am using the git version
