### ISSUE TITLE
Patch for "commit" for 2.4.x

### ISSUE THREAD

**Issue by aorourke123** [mrklein/openfoam-os-x#57]
Hello.

What is the proper patch "commit" number for 2.4.x?

Thank you,
Aubrie

**Comment by aorourke123** [comment]
Overall, I am having a hard time adding OpenFoam 2.3.x or 2.4.x to MacOS catalina. Any hints?

**Comment by aorourke123** [comment]
I could only find the 2.3.x patch because I could not make the 2.4.x work, please see outcome:

OpenFOAM-2.3.x-Mac.patch:753: trailing whitespace.
        handle = 
OpenFOAM-2.3.x-Mac.patch:1311: trailing whitespace.
       
OpenFOAM-2.3.x-Mac.patch:1340: trailing whitespace.
 
OpenFOAM-2.3.x-Mac.patch:1579: trailing whitespace.
c++DBUG     = 
OpenFOAM-2.3.x-Mac.patch:1605: trailing whitespace.
cDBUG       = 
error: patch failed: applications/solvers/incompressible/adjointShapeOptimizationFoam/Make/options:6
error: applications/solvers/incompressible/adjointShapeOptimizationFoam/Make/options: patch does not apply
error: patch failed: applications/solvers/multiphase/multiphaseEulerFoam/Make/options:17
error: applications/solvers/multiphase/multiphaseEulerFoam/Make/options: patch does not apply
error: patch failed: applications/utilities/postProcessing/turbulence/createTurbulenceFields/Make/options:5
error: applications/utilities/postProcessing/turbulence/createTurbulenceFields/Make/options: patch does not apply
error: patch failed: applications/utilities/postProcessing/wall/wallShearStress/Make/options:7
error: applications/utilities/postProcessing/wall/wallShearStress/Make/options: patch does not apply
error: patch failed: etc/config/scotch.sh:36
error: etc/config/scotch.sh: patch does not apply
error: patch failed: etc/config/settings.sh:391
error: etc/config/settings.sh: patch does not apply
error: patch failed: src/OSspecific/POSIX/printStack.C:53
error: src/OSspecific/POSIX/printStack.C: patch does not apply
error: patch failed: src/parallel/decompose/ptscotchDecomp/Make/options:8
error: src/parallel/decompose/ptscotchDecomp/Make/options: patch does not apply

**Comment by mrklein** [comment]
Hi,

Commit SHA is a part of patch name: 2b147f4. Patch applies without any problems.

On Big Sur with clang 12.0.0 it is necessary to add more modifications due to outdated code in OpenFOAM and CGAL version change (library became header-only, so there is no need to link foamyHexMesh). I do not know yet, how to publish these changes: either as a separate patch, or as an update.

Could you describe your difficulties on Catalina?

Concerning your question about version 2.3.0, it seems you are trying to apply the patch twice.

**Comment by aorourke123** [comment]
I will try again with the commit you have provided for the openfoam 2.3.X patch above. By Catalina difficulty was with macports and now it is with the git and homebrew version.

I was trying to see if the 2.3.X patch would apply to either openfoam version. That is why is looks like I am applying it twice. I was trying to show that both had failed.

**Comment by mrklein** [comment]
You CANNOT:
- Use provided commit SHA for OpenFOAM 2.3.x.
- Use version 2.4.x patch for OpenFOAM 2.3.x.

Either you clone 2.4.x repository, checkout specified commit, apply patch (from this repository) and compile OpenFOAM. OR you install Macports, clone 2.3.x repository and proceed with Bernhard Gschaider's patch.

Yet, either way you will need to resolve CGAL and PackedBoolList compilation problems. CGAL is not crucial, as it is used only in foamyHexMesh and can be disabled, but the problem with private inheritance in PackedBoolList halts compilation in the very beginning.

**Comment by mrklein** [comment]
It seems, bug is not relevant any more.
