### ISSUE TITLE
Using APFS Case-sensitive volume instead of HFS+ sparsebundle

### ISSUE THREAD

**Issue by BrushXue** [mrklein/openfoam-os-x#59]
Tested with Big Sur 11.2, OFv2012. APFS volumes share disk space dynamically so there's no space limit like the HFS+ sparsebundle. Needs macOS 10.13+. It can be added to the wiki page to simplify installation.
1. Create a APFS Case-sensitive volume in Disk Utility, named 'OpenFOAM'
![Screen Shot 2021-02-09 at 1 25 49 PM](https://user-images.githubusercontent.com/12702149/107409600-5831b700-6ada-11eb-8d70-523fd1b57f0e.png)
2. Create a symbolic link
```
ln -s /Volumes/OpenFOAM $HOME/
```
Or edit `/etc/fstab` to mount it directly
All set.

**Comment by mrklein** [comment]
Hi,

Thank you for the hint. I will add this variant of case-sensitive filesystem creation to a separate guide. Except, instead of using GUI, volume will be created from command line:

```sh
$ diskutil apfs addVolume disk1 'Case-sensitive APFS' OpenFOAM
```

**Comment by mrklein** [comment]
I have added a guide for creation of APFS volume (https://github.com/mrklein/openfoam-os-x/wiki/APFS-volume).

BTW you solution with symlink does not work with Foundation version, so instead of `$HOME/OpenFOAM` one has to use `/Volumes/OpenFOAM`, which works both in Foundation, and in ESI versions.

**Comment by mrklein** [comment]
Here is link to the wiki: https://github.com/mrklein/openfoam-os-x/wiki/APFS-volume
