### ISSUE TITLE
Too man open files issues on OS X 10.11.0

### ISSUE THREAD

**Issue by effi** [mrklein/openfoam-os-x#6]
I get a lot of "osx could not open file XXXX.C/H due to Too many open files" issues.
Not sure if they are a dealbreaker (but I think so), but executing

>ulimit -n 4096

before ./Allwmake seems to have solved the problem.

Its compiling atm, will post an update afterwards

**Comment by effi** [comment]
Yep, ulimit -n 4096 made it compile flawless

**Comment by mrklein** [comment]
Thanks for the report. I have added ulimit invocation before Allwmake to the guides.

**Comment by effi** [comment]
Btw, works great on El Capitan, at least 2.3.1 runs without any yet discovered glitches for me

**Comment by mrklein** [comment]
Fixed by ea1c09c06c757786e54d0ecc1fc280f58c49e299
