### ISSUE TITLE
Problem with surfaceBooleanFeatures

### ISSUE THREAD

**Issue by BrushXue** [mrklein/openfoam-os-x#64]
Hello.

I was trying to run the tutorial case in `tutorials/mesh/foamyHexMesh/mixerVessel` and got the following error when running `surfaceBooleanFeatures`:
```
dyld: lazy symbol binding failed: Symbol not found: ___gmpq_init
  Referenced from: /Users/gux215/OpenFOAM/OpenFOAM-v2012/platforms/darwin64ClangDPInt32Opt/lib/libPolyhedronReader.dylib
  Expected in: flat namespace

dyld: Symbol not found: ___gmpq_init
  Referenced from: /Users/gux215/OpenFOAM/OpenFOAM-v2012/platforms/darwin64ClangDPInt32Opt/lib/libPolyhedronReader.dylib
  Expected in: flat namespace
```
Tested on another Linux computer and didn't receive any error message. I wonder if this issue comes from the homebrew CGAL?
Thanks.

**Comment by mrklein** [comment]
Hi,

In fact, it is missing `-lgmp -lmpfr` in `CGAL_LIBS` (in `wmake/rules/darwin64Clang/cgal`).

**Comment by mrklein** [comment]
Though, after you will get `sigFpe` during `foamyHexMesh` run. Yet, this behaviour is identical to Linux.

**Comment by BrushXue** [comment]
This is weird as it's opposite to https://develop.openfoam.com/Development/openfoam/-/wikis/building#darwin-mac-os

**Comment by mrklein** [comment]
Guess, Homebrew maintainers of CGAL do not follow OpenFOAM's suggestions:

```
class Cgal < Formula
...
  depends_on "cmake" => [:build, :test]
  depends_on "qt@5" => [:build, :test]
  depends_on "boost"
  depends_on "eigen"
  depends_on "gmp"
  depends_on "mpfr"
...
```

And `___gmpq_init`, which dynamic linker cannot find, is a function from GMP.

**Comment by mrklein** [comment]
Guess, the issue became irrelevant.
