### ISSUE TITLE
The patch for OpenFOAM v2106

### ISSUE THREAD

**Issue by gangw0632** [mrklein/openfoam-os-x#65]
Hi!

I'd like to know when would the MacOS patch for OpenFOAM v2106 be released? Thanks!

Best,
Gang

**Comment by mrklein** [comment]
Though v2106 can be built without any patches, here it is for you: https://github.com/mrklein/openfoam-os-x/blob/master/OpenFOAM-v2106.patch. Please test it and report any problems.
