### ISSUE TITLE
Link broken: Guides for specific versions OpenFOAM-v1912

### ISSUE THREAD

**Issue by aqeelahmed168** [mrklein/openfoam-os-x#66]
I guess there was a guide for specific OpenFOAM-v1912 but it seems that the link is broken now

https://github.com/mrklein/openfoam-os-x/wiki/OpenFOAM(R)-v1912-and-Homebrew

**Comment by mrklein** [comment]
Thanks for the report. In fact, I did not finish this guide, so the link sneaked to the index by mistake. I have removed it (anyway it was outdated).
