### ISSUE TITLE
OpenFOAM v2112 and Mac OS 12

### ISSUE THREAD

**Issue by aqeelahmed168** [mrklein/openfoam-os-x#75]
It is not an issue, but could be useful for new comers.

I have recently tried to build the OpenFOAM v2121 on Mac OS Monterey 12.1
It seems that now the patches are integrated and no additional patch is required.

I compiled everything here in case someone needs it.
https://www.linkedin.com/feed/update/urn:li:ugcPost:6881262545705992193?updateEntityUrn=urn%3Ali%3Afs_updateV2%3A%28urn%3Ali%3AugcPost%3A6881262545705992193%2CFEED_DETAIL%2CEMPTY%2CDEFAULT%2Cfalse%29

**Comment by OP-Luffy** [comment]
Thanks, but I can't open the link.

**Comment by aqeelahmed168** [comment]
You can find same info here as well.
https://www.researchgate.net/publication/357395955_OpenFOAM_installation_on_Mac

**Comment by OP-Luffy** [comment]
@aqeelahmed168 Thanks for your great help!  Finally I can use OpenfFOAM on my mac!

**Comment by Boris3305** [comment]
It seems not work for me. When I try to run the Allwmake, a clang error and a make error 254 happened
