### ISSUE TITLE
Encountered C++ import errors when making 

### ISSUE THREAD

**Issue by minhtriet** [mrklein/openfoam-os-x#79]
When running `Allwmake`, I received the following errors
```
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/algorithm:641:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:79:9: error: no member named 'strxfrm' in the global namespace
using ::strxfrm;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:80:9: error: no member named 'memchr' in the global namespace
using ::memchr;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:81:9: error: no member named 'strchr' in the global namespace
using ::strchr;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstring:82:9: error: no member named 'strcspn' in the global namespace
using ::strcspn;
      ~~^
```
What is the reason for this? Thank you

**Comment by mrklein** [comment]
Hi,

Thank you for the report, it would be nice to know:

- OpenFOAM(R) version
- macOS version (`sw_vers`)
- CLT version (`clang++ --version`)

**Comment by minhtriet** [comment]
Thank you for the swift answer. My config is
- OpenFOAM 9.20211007
- Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1217
- CLT
 ```Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin```

**Comment by minhtriet** [comment]
Hi, thank you. I ran everything again and was _almost_ able to build OpenFoam. 

The built finishes, but I received the error `u/OpenFOAM/OpenFOAM-9/etc/config.sh/mpi: line 46: mpicc: command not found` when trying to run OpenFOAM. I ran `mpicc --version` and the result is 
```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Rechecking my installation again

**Comment by mrklein** [comment]
Is this strange issue still relevant?

**Comment by minhtriet** [comment]
I gave up on it and used SimScale for my problem instead. Sorry.
