### ISSUE TITLE
clang: error when allmake

### ISSUE THREAD

**Issue by Boris3305** [mrklein/openfoam-os-x#80]
when I run the Allwmake , it doesnt work at final. In log.Al, it say this:
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
.....
make: *** [/Users/boris/OpenFOAM/OpenFOAM-v2112/build/darwin64ClangDPInt32Opt/src/meshTools/triSurface/triSurfaceTools/geompack/geompack.o] Error 254

**Comment by mrklein** [comment]
Hi,

I can confirm, the error. It happens during compilation of `geompack.C`. And it seems, there is a problem with compiler flags, as without flags file is compiled without problem.

**Comment by mrklein** [comment]
Possible work-around is to add `#pragma clang fp exceptions(ignore)` at the top of `triSurface/triSurfaceTools/geompack/geompack.C`. This will switch off trapping math for this file.

**Comment by Boris3305** [comment]
Thank u for your advice!
 It's not cause by the goepack.c . It's problem of the Xcode. After I change the Xcode 13.x to 12.5, everything is done.  :)

**Comment by mrklein** [comment]
It is a problem of clang 13.1.6 not being able to compile `geompack.C` with `-O3` and `-ftrapping-math` flags. So, using `#pragma clang fp exceptions(ignore)`, I switch off `-ftrapping-math` flag for `geompack.C`, which fixes the problem of compilation.

Yes, you can also switch compilers. Though, adding a line to a file seems to be simpler, than downgrading of Xcode.

**Comment by Boris3305** [comment]
OK. I got it.
THANKS!
