### ISSUE TITLE
OpenFOAM 10

### ISSUE THREAD

**Issue by matteoicardi** [mrklein/openfoam-os-x#81]
anyone tried to compile OF10? is the dev patch enough?

**Comment by mrklein** [comment]
There were minor conflicts during dev patch application (which can be ignored).

Concerning your flex problem: I cannot reproduce it. With

```
$ flex --version
flex 2.6.4 Apple(flex-34)
```

Everything is built without any difficulties.

**Comment by mrklein** [comment]
I have added OpenFOAM 10 patch. It compiles without any problems on

```
$ sw_vers 
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
```

with

```
$ clang++ --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by matteoicardi** [comment]
Thanks @mrklein ! the problem with flex I had was because I was using the homebrew version. I switched back to the Apple version and it works fine.
