### ISSUE TITLE
Updated path for OpenFOAM v10

### ISSUE THREAD

**Issue by aqeelahmed168** [mrklein/openfoam-os-x#85]
Hi,

Is is possible to have the path for OpenFOAM v10 after this commit (13th April 2023): 73bdbb2a3c7b82bbe554ca304180b20b6a931591

**Comment by mrklein** [comment]
Hi,

It seems patch for the old commit applies fine on the new source state (though, I did not try to compile yet). Are there compilation problems?

**Comment by aqeelahmed168** [comment]
Hi,

I checked and the old patch works as well.
